version: '2'
services:
  ideaboard-api:
    container_name: ideaboard-api
    build: .
    environment:
      - PASSENGER_APP_ENV=development
    ports:
      - "80:80"
    volumes:
      - .:/home/app/ideaboard-api
#   postgres:
#     image: posdocker exec -it todoapi bashtgres:9.6.6
#     container_name: tododb
#     environment:
#       - POSTGRES_PASSWORD=mysecretpassword
#       - POSTGRES_USER=todoapi
#       - POSTGRES_DB=todoapi_development
#     volumes_from:
#       - postgres_data
#   postgres_data:
#       container_name: tododb_data
#       image: postgres:9.6.6
#       volumes:
#         - pgdata:/var/lib/postgresql/data
#       command: /bin/true

# volumes:
#   pgdata:
#     external: true